[hardware]
  model = "E5080B"
  address = "TCPIP0::192.168.1.78::inst0::INSTR"
  attenuation = 75
  port = "S43"

[sample]
  name = "ITRI"


[[measurement]]
  label = "C100"
  output = "D:\\Data\\resonator\\test"

  IF_bandwidth = 200
  power = 0
  repeat = 3
  [measurement.frequency]
    start = 5.725e9
    stop = 5.760e9
    points = 1001
  
[[measurement]]
  label = "C200"
  output = "D:\\Data\\resonator\\test"

  IF_bandwidth = 200
  power = 0
  repeat = 2
  [measurement.frequency]
    start = 5.725e9
    stop = 5.760e9
    points = 1001
  