[hardware]
  model = "E5080B"
  address = "TCPIP0::192.168.1.78::inst0::INSTR"
  attenuation = 80
  port = "S21"

[sample]
  name = "ITRI"


[[measurement]]
  label = "C100"
  output = "C:\\Users\\ASUS\\Documents\\python training\\THINFAT"

  IF_bandwidth = 1000
  power = -20
  repeat = 1
  [measurement.frequency]
    start = 5.9002e9
    stop = 5.90055e9
    points = 501