[hardware]
  model = "ZNB"
  address = 'TCPIP0::192.168.50.249::inst0::INSTR'
  attenuation = 80
  port = "S43"

[sample]
  name = "ITRI"


[[measurement]]
  label = "test"
  output = "C:\\Users\\ASUS\\Documents\\python training\\lite_testing"

  IF_bandwidth = 1000
  power = -20
  repeat = 1
  [measurement.frequency]
    start = 4e9
    stop = 8e9
    points = 501