[hardware]
  model = "ZNB"
  address = "TCPIP0::192.168.1.123::inst0::INSTR"
  attenuation = 80
  port = "S21"

[sample]
  name = "resonator0622"


[[measurement]]
  label = "test"
  output = "data/lite_testing"

  IF_bandwidth = 200
  power = -20.0
  repeat = 1
  [measurement.frequency]
    start = 4000000000.0
    stop = 8000000000.0
    points = 8001