[hardware]
  model = "ZNB"
  address = "TCPIP0::192.168.1.123::inst0::INSTR"
  attenuation = 80
  port = "S43"

[sample]
  name = "thinfat"


[[measurement]]
  label = "test"
  output = "data/lite_testing"

  IF_bandwidth = 100
  power = -20.0
  repeat = 1
  [measurement.frequency]
    start = 1000000000.0
    stop = 20000000000.0
    points = 1001