[hardware]
  model = "ZNB"
  address = "TCPIP0::192.168.1.123::inst0::INSTR"
  attenuation = 80
  port = "S43"

[sample]
  name = "resonator06234"

[[measurement]]
  IF_bandwidth = 1000
  power = -20.0
  [measurement.frequency]
    deltafre = 100e6
    resonator_fre = 12.05e9
    points = 501
