[hardware]
model = "ZNB"
address = "TCPIP0::192.168.1.123::inst0::INSTR"
attenuation = 80
port = "S21"

[sample]
name = "resonator0622"

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -50.0
repeat = 1
output = "data/raw/C46090/att80_-50.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -45.0
repeat = 1
output = "data/raw/C46090/att80_-45.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -40.0
repeat = 1
output = "data/raw/C46090/att80_-40.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -35.0
repeat = 1
output = "data/raw/C46090/att80_-35.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -30.0
repeat = 1
output = "data/raw/C46090/att80_-30.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -25.0
repeat = 1
output = "data/raw/C46090/att80_-25.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -20.0
repeat = 1
output = "data/raw/C46090/att80_-20.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -15.0
repeat = 1
output = "data/raw/C46090/att80_-15.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -10.0
repeat = 1
output = "data/raw/C46090/att80_-10.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = -5.0
repeat = 1
output = "data/raw/C46090/att80_-5.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C46090"
IF_bandwidth = 20
power = 0.0
repeat = 1
output = "data/raw/C46090/att80_0.0"

[measurement.frequency]
start = 4608362000.0
stop = 4610253000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -50.0
repeat = 1
output = "data/raw/C48230/att80_-50.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -45.0
repeat = 1
output = "data/raw/C48230/att80_-45.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -40.0
repeat = 1
output = "data/raw/C48230/att80_-40.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -35.0
repeat = 1
output = "data/raw/C48230/att80_-35.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -30.0
repeat = 1
output = "data/raw/C48230/att80_-30.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -25.0
repeat = 1
output = "data/raw/C48230/att80_-25.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -20.0
repeat = 1
output = "data/raw/C48230/att80_-20.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -15.0
repeat = 1
output = "data/raw/C48230/att80_-15.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -10.0
repeat = 1
output = "data/raw/C48230/att80_-10.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = -5.0
repeat = 1
output = "data/raw/C48230/att80_-5.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C48230"
IF_bandwidth = 20
power = 0.0
repeat = 1
output = "data/raw/C48230/att80_0.0"

[measurement.frequency]
start = 4822364000.0
stop = 4824157000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -50.0
repeat = 1
output = "data/raw/C58270/att80_-50.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -45.0
repeat = 1
output = "data/raw/C58270/att80_-45.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -40.0
repeat = 1
output = "data/raw/C58270/att80_-40.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -35.0
repeat = 1
output = "data/raw/C58270/att80_-35.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -30.0
repeat = 1
output = "data/raw/C58270/att80_-30.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -25.0
repeat = 1
output = "data/raw/C58270/att80_-25.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -20.0
repeat = 1
output = "data/raw/C58270/att80_-20.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -15.0
repeat = 1
output = "data/raw/C58270/att80_-15.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -10.0
repeat = 1
output = "data/raw/C58270/att80_-10.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = -5.0
repeat = 1
output = "data/raw/C58270/att80_-5.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C58270"
IF_bandwidth = 20
power = 0.0
repeat = 1
output = "data/raw/C58270/att80_0.0"

[measurement.frequency]
start = 5825789000.0
stop = 5828091000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -50.0
repeat = 1
output = "data/raw/C59085/att80_-50.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -45.0
repeat = 1
output = "data/raw/C59085/att80_-45.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -40.0
repeat = 1
output = "data/raw/C59085/att80_-40.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -35.0
repeat = 1
output = "data/raw/C59085/att80_-35.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -30.0
repeat = 1
output = "data/raw/C59085/att80_-30.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -25.0
repeat = 1
output = "data/raw/C59085/att80_-25.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -20.0
repeat = 1
output = "data/raw/C59085/att80_-20.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -15.0
repeat = 1
output = "data/raw/C59085/att80_-15.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -10.0
repeat = 1
output = "data/raw/C59085/att80_-10.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = -5.0
repeat = 1
output = "data/raw/C59085/att80_-5.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59085"
IF_bandwidth = 20
power = 0.0
repeat = 1
output = "data/raw/C59085/att80_0.0"

[measurement.frequency]
start = 5906889000.0
stop = 5909727000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -50.0
repeat = 1
output = "data/raw/C59915/att80_-50.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -45.0
repeat = 1
output = "data/raw/C59915/att80_-45.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -40.0
repeat = 1
output = "data/raw/C59915/att80_-40.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -35.0
repeat = 1
output = "data/raw/C59915/att80_-35.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -30.0
repeat = 1
output = "data/raw/C59915/att80_-30.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -25.0
repeat = 1
output = "data/raw/C59915/att80_-25.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -20.0
repeat = 1
output = "data/raw/C59915/att80_-20.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -15.0
repeat = 1
output = "data/raw/C59915/att80_-15.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -10.0
repeat = 1
output = "data/raw/C59915/att80_-10.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = -5.0
repeat = 1
output = "data/raw/C59915/att80_-5.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501

[[measurement]]
label = "C59915"
IF_bandwidth = 20
power = 0.0
repeat = 1
output = "data/raw/C59915/att80_0.0"

[measurement.frequency]
start = 5990273000.0
stop = 5993033000.0
points = 501
