

[hardware]
  model = "ZNB"
  address = "TCPIP0::192.168.1.123::inst0::INSTR"
  attenuation = 80
  port = "S43"

[sample]
  name = "thinfat"

[output]
  data_path = "data/raw"
[[resonator]]
  label = "C12050"
  IF_bandwidth = 20
  [resonator.snr]
    max_repeat = 5
    min_repeat = 1
    power_ave_ratio = -140

  [resonator.power]
    min = -50
    max = 0
    step = 5
  [resonator.frequency]
    start = 11.258342e9  # 填入優化後的 start
    stop = 12.842470e9   # 填入優化後的 stop
    points = 501
