# Empty config

[[resonator]]
label = "C61500"
IF_bandwidth = 20
snr = {max_repeat = 10, min_repeat = 1, power_ave_ratio = -120.0}
power = {min = -60.0, max = 0.0, step = 5.0}
frequency = {start = 6149678018.056584, stop = 6150322103.258498, points = 501}
[output]
data_path = "data/TestDummy_0629_20260630_121251"

[hardware]
  model = "DUMMY"
  address = "DUMMY_VISA_ADDRESS"
  attenuation = 80
  port = "S21"

[sample]
  name = "TestDummy_0629" # 樣品名稱

