

[hardware]
  model = "E5080B"
  address = "TCPIP0::192.168.1.78::inst0::INSTR"
  attenuation = 109
  port = "S21"

[sample]
  name = "ITRI_364_scalinQ"

[output]
  task_path = "D:\\Data\\resonator\\ITRI_364_scalinQ\\task"
  data_path = "D:\\Data\\resonator\\ITRI_364_scalinQ\\data"

[[resonator]]
  label = "C46277"
  IF_bandwidth = 20
  [resonator.snr]
    max_repeat = 50
    min_repeat = 2
    power_ave_ratio = -140

  [resonator.power]
    min = -60
    max = -20
    step = 5
  [resonator.frequency]
    start = 4.62755e9
    stop = 4.62780e9
    points = 501
